### ISSUE TITLE
diff is reset, but never used

### ISSUE THREAD

**Issue by oyvindeide** [equinor/snapwell#40]
This `diff` is reset, but never used:
https://github.com/equinor/snapwell/blob/8233707cb746854898b70e0714edf7dbcbf2123c/snapwell/snapecl.py#L326

Instead we do `logs["TVD_DIFF"].append(new_tvd - z)` should that be `logs["TVD_DIFF"].append(diff)`?

**Comment by eivindjahren** [comment]
I think the code is correct altough surprising. I suggest the following refactoring:
 ```
        diff = z - new_tvd
        if abs(diff) > 100:
            logging.warning("Observed a vertical adjustment of %d m.  Ignoring.", diff)
            new_tvd = z
            logs["TVD_DIFF"].append(0)
        else:
           logs["TVD_DIFF"].append(diff)
```
